name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run tests on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov pytest-asyncio
        python -m pip install -e .[dev]
        
    - name: Run tests
      run: |
        pytest tests/ --cov=mcpwire --cov-branch --cov-report=xml
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: anukchat/mcpwire
        
    - name: Lint with flake8
      if: ${{ matrix.python-version == '3.10' }}
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 mcpwire --count --select=E9,F63,F7,F82 --show-source --statistics
        # Check for general code quality issues (only on Python 3.10 job)
        flake8 mcpwire --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics 